- name: Install Chromium
  pacman:
    name: chromium
    state: present

- name: Install chromium-widevine
  aur:
    name: chromium-widevine
    user: '{{ user.name }}'
  when: chromium.widevine is sameas True
