- name: Install Postfix
  pacman:
    name: postfix
    state: present

- name: Configure Postfix
  include: configure.yml

- name: Enable Postfix service
  systemd:
    name: postfix.service
    enabled: True
    state: started
