- name: Install Android Tools
  pacman:
    name:
      - android-tools
      - android-udev

- name: Add user to plugdev group
  user:
    name: '{{ user.name }}'
    append: True
    groups: plugdev
