# MacBookAir6,2 ICC profile
# Installs xcalib from the AUR and copies the ICC profile for a MacBookAir6,2
# with a Samsung display to /usr/local/share/color/icc/. LG also provided
# panels for some units of this model: the role will not make any distinctions,
# but the profile may not be correct for these machines. The ICC profile can be
# applied by adding the following to your .xinitrc:
# /usr/bin/xcalib -display :0 \
#   "/usr/local/share/color/icc/Color LCD-933C106C-08BC-09AA-F750-C2A74A119DEF.icc"

- name: Install xcalib
  aur:
    name: xcalib
    user: '{{ user.name }}'

- name: Copy ICC profile
  copy:
    src: 'Color LCD-933C106C-08BC-09AA-F750-C2A74A119DEF.icc'
    dest: /usr/local/share/color/icc/
