- name: Install virtualisation packages
  pacman:
    name:
      # libvirt and its optional dependencies; dmidecode required to supress errors
      - libvirt
      - bridge-utils
      - dmidecode
      - dnsmasq
      - ebtables
      - openbsd-netcat
      - qemu-headless
      # To create virtual machines
      - virt-install
    state: present

- name: Enable nested KVM
  lineinfile:
    path: /etc/modprobe.d/kvm_intel.conf
    create: True
    line: 'options kvm_intel nested=1'
    state: present
  notify:
    - Generate initramfs
    - Reload kvm_intel module

- name: Enable libvirt hostname resolution
  replace:
    path: /etc/nsswitch.conf
    regexp: '^hosts:\s+files\s+(?!libvirt)'
    replace: 'hosts: files libvirt '

- meta: flush_handlers

- name: Enable and start libvirt services
  systemd:
    name: '{{ item }}'
    enabled: True
    state: started
  with_items:
    - libvirtd.service
    - libvirt-guests.service

- name: Add user to libvirt group
  user:
    name: '{{ user.name }}'
    groups: libvirt
    append: True
